---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Instalar dependencias para ost
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{ ost_dependencies }}"

- name: Creando directorio para proyecto
  ansible.builtin.file:
    path: "{{ ost_root_path }}"
    state: directory
    owner: "{{ usuario_apache }}"
    group: "{{ grupo_apache }}"
    mode: 0755

- name: "Descarga y descomprime osticket {{ ost_18 }}"
  ansible.builtin.unarchive:
    src: "https://github.com/osTicket/osTicket/releases/download/v{{ ost_18 }}/osTicket-v{{ ost_18 }}.zip"
    dest: "{{ ost_root_path }}"
    remote_src: true

- name: Copiando archivos de configuración
  ansible.builtin.copy:
    src: "{{ ost_root_path }}/upload/include/ost-sampleconfig.php"
    dest: "{{ ost_root_path }}/upload/include/ost-config.php"
    mode: 0666
    remote_src: true