---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Instalacion mariaDB
  ansible.builtin.apt:
    name: [ 'mariadb-server', 'python3-pymysql' ]
    update_cache: true
    cache_valid_time: 3600

- name: Creando mariaDB root password
  ansible.builtin.mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Eliminar acceso anonimo
  ansible.builtin.mysql_user:
    name: ''
    host: localhost
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Elimina la base de datos test
  ansible.builtin.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Crea la base de datos para osticket
  ansible.builtin.mysql_db:
    name: osticket_db
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: "Crea el usuario {{ usuario }}"
  ansible.builtin.mysql_user:
    name: "{{ usuario }}"
    password: "{{ password }}"
    host: localhost
    state: present
    update_password: on_create
    priv: "{{ db }}.*:ALL"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: iniciar_mariadb